# -*- coding: utf-8 -*-
"""DAV1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tiw7uqr8jgQCk8FwE8r0QdHcCtYHY1E0
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv(r"Iris.csv")

print(df.shape)

print(df.head())

print(df.tail())

print(df.columns)

df.info()

print(df.isnull().sum())

df=df.dropna()
print(df.isnull().sum())

print(df.duplicated().sum())

df=df.drop_duplicates()
print(df.duplicated().sum())

print(df.describe())
sns.set_style("darkgrid")

plt.figure(figsize=(8,5))
sns.histplot(data=df, x="SepalLengthCm",bins=10)
plt.title("Distribution of Sepal length")
plt.xlabel("Sepal length (cm)")
plt.ylabel("Number of flowers")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x="Species",y="SepalLengthCm")
plt.title("Sepal Length by Species")
plt.xlabel("Species")
plt.ylabel("Sepal Length (cm)")

plt.figure(figsize=(10,7))
sns.scatterplot(
    data=df,
    x="SepalLengthCm",
    y="PetalLengthCm",
    hue="Species"
)
plt.title("Sepal Length VS Petal Length")
plt.xlabel("Sepal Length (cm)")
plt.ylabel("Petal Length (cm)")

sns.pairplot(df,hue="Species")
plt.show()

numeric_columns=[
    "SepalLengthCm",
    "SepalWidthCm",
    "PetalLengthCm",
    "PetalWidthCm"
]
correlation = df[numeric_columns].corr()
print(correlation)
plt.figure(figsize=(8,5))
sns.heatmap(correlation,annot=True,cmap="coolwarm",fmt=".2f")
plt.title("Correlation heatmap")
plt.show()





